preserve_hierarchy: true
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
commit_message: "[skip ci] chore(i18n): sync translations from crowdin"
pull_request_title: "Sync Translations from Crowdin"
pull_request_body: "This is an automated pull request to sync translations from [Crowdin](https://crowdin.com/project/reactive-resume)."
pull_request_labels:
  - l10n
pull_request_reviewers:
  - amruthpillai
files:
  - source: apps/web/locales/en-US.po
    translation: apps/web/locales/%locale%.%file_extension%
