packages:
  - apps/*
  - packages/*
  - tooling
patchedDependencies:
  '@react-pdf/textkit@6.3.0': patches/@react-pdf__textkit@6.3.0.patch
minimumReleaseAge: 0
onlyBuiltDependencies:
  - bcrypt
  - esbuild
  - lefthook
  - msgpackr-extract
  - msw
  - pdfjs-dist
  - sharp
overrides:
  postcss@<8.5.10: ^8.5.14
